create or replace FUNCTION GENERATE_PASSWORD(V_LENGTH NUMBER) RETURN VARCHAR2 IS
    MY_STR VARCHAR2(4000);
BEGIN
    FOR I IN 1..V_LENGTH LOOP
        MY_STR := MY_STR || DBMS_RANDOM.STRING(
            CASE WHEN DBMS_RANDOM.VALUE(0, 1) < 0.5 THEN 'l' ELSE 'x' END, 1);
    END LOOP;
    RETURN MY_STR;
END;