create or replace TRIGGER TRG_PY_PT_ABSENT_PROCESS AFTER INSERT OR UPDATE OR DELETE ON PY_PT_ABSENT FOR EACH ROW
  DECLARE
    Type Tprocess is ref Cursor;
       ref_process Tprocess;
         i PY_PT_SAL_HD%ROWTYPE;
         j PY_GM_ACCT_YEARS%ROWTYPE;
         vcount   NUMBER(2);
    /*CRAETE BY SAROJ KUMAR GIRI*/
    BEGIN
   
       i.COMP_AID:=CASE WHEN INSERTING THEN :NEW.COMP_AID WHEN DELETING THEN :OLD.COMP_AID WHEN UPDATING THEN :OLD.COMP_AID END ;

            OPEN ref_process FOR
            SELECT YEAR_ID FROM PY_GM_ACCT_YEARS WHERE  COMP_ID=i.COMP_AID AND IS_YEAR_OPEN='Y';
            FETCH ref_process INTO j.YEAR_ID;
            CLOSE ref_process;
    
            OPEN ref_process FOR
            SELECT COUNT(PAY_MONTH),PAY_MONTH FROM PY_PM_MONTH_STATUS WHERE ACC_YEAR=j.YEAR_ID AND STATUS='0' AND MONTH_LOCK='0' AND COMP_AID=i.COMP_AID
            GROUP BY PAY_MONTH
            ;
            FETCH ref_process INTO vcount,i.PAY_MONTH;
            CLOSE ref_process;
    
--            OPEN ref_process FOR
--            SELECT PAY_MONTH FROM PY_PM_MONTH_STATUS WHERE ACC_YEAR=j.YEAR_ID AND STATUS='0' AND MONTH_LOCK='0' AND COMP_AID=i.COMP_AID;
--            FETCH ref_process INTO i.PAY_MONTH;
--            CLOSE ref_process;
    

    
    IF vcount=1 THEN
    
            CASE WHEN INSERTING THEN 
            UPDATE TBL_PY_PT_SAL_PROCESS_CHNG SET CHANGE_FLAG='Y' ,UP_DATE=SYSDATE, UP_USER=:NEW.USER_CR 
            WHERE COMP_AID=:NEW.COMP_AID AND EMP_AID=:NEW.EMP_AID AND ACC_YEAR=j.YEAR_ID AND PAY_MONTH=i.PAY_MONTH;
            WHEN DELETING THEN
            UPDATE TBL_PY_PT_SAL_PROCESS_CHNG SET CHANGE_FLAG='Y' ,UP_DATE=SYSDATE, UP_USER=:OLD.USER_CR 
            WHERE COMP_AID=:OLD.COMP_AID AND EMP_AID=:OLD.EMP_AID AND ACC_YEAR=j.YEAR_ID AND PAY_MONTH=i.PAY_MONTH;
            WHEN UPDATING THEN
            UPDATE TBL_PY_PT_SAL_PROCESS_CHNG SET CHANGE_FLAG='Y' ,UP_DATE=SYSDATE, UP_USER=:OLD.USER_AT 
            WHERE COMP_AID=:OLD.COMP_AID AND EMP_AID=:OLD.EMP_AID AND ACC_YEAR=j.YEAR_ID AND PAY_MONTH=i.PAY_MONTH;
            END CASE;
    
    END IF;
    
END;